image: docker:stable
services:
  - docker:stable-dind

variables:
  CATALOGUE_NAME: elwazi

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - set | grep CI_REGISTRY
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
  - docker build --pull -t "$DOCKER_IMAGE_NAME" .
  - docker push "$DOCKER_IMAGE_NAME"
  - |
    if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
      docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
      docker push "$CI_REGISTRY_IMAGE:latest"
    fi

deploy:
  image: dtzar/helm-kubectl:3.11.0
  stage: deploy
  tags:
  - dind
  variables:
    DOCKER_IMAGE_NAME: data-catalogue-demo
  before_script:
  - kubectl config set-context --current --namespace=${KUBECTL_NAMESPACE}
  script:
    - kubectl config view --minify | grep namespace
    # kustomize is not available on the image, so using yq instead
    - yq -i ".images[0].newTag = \"${CI_COMMIT_REF_SLUG}\"" k8s/overlays/${CATALOGUE_NAME}/kustomization.yaml
    - yq -i ".images[0].newName = \"${CI_REGISTRY_IMAGE}\"" k8s/overlays/${CATALOGUE_NAME}/kustomization.yaml
    - cp ${DOCKER_CONFIG_JSON} k8s/overlays/${CATALOGUE_NAME}/.dockerconfig.json
    - cat k8s/overlays/${CATALOGUE_NAME}/.dockerconfig.json
    - kubectl apply -k k8s/overlays/${CATALOGUE_NAME}
    - kubectl rollout restart deployments data-catalogue-${CATALOGUE_NAME}
    - kubectl wait --for=condition=ready pod --selector=app=data-catalogue-${CATALOGUE_NAME} --timeout=60s


