image: docker:stable
services:
  - docker:stable-dind

variables:
  CATALOGUE_NAME: elwazi

stages:
  - build
  - deploy


build:
  stage: build
  tags:
    - dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - set | grep CI_REGISTRY
  script:
  - docker build --pull -t "$DOCKER_IMAGE_NAME" .
  - docker push "$DOCKER_IMAGE_NAME"
  - |
    if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
      docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
      docker push "$CI_REGISTRY_IMAGE:latest"
    fi

deploy:
  image: dtzar/helm-kubectl:3.11.0
  stage: deploy
  tags:
  - dind
  before_script:
    - kubectl config set-context --current --namespace=${KUBECTL_NAMESPACE}

  script:
    - kubectl config view --minify | grep namespace
    - cd k8s/overlays/${CATALOGUE_NAME}
    - kustomize edit set image $DOCKER_IMAGE_NAME=$DOCKER_IMAGE_TAG
    - cd -
    - kubectl apply -k k8s/overlays/${CATALOGUE_NAME}
    - kubectl rollout restart deployments data-catalogue-${CATALOGUE_NAME}
    - kubectl wait --for=condition=ready pod --selector=app=data-catalogue-${CATALOGUE_NAME} --timeout=60s


