apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dc-elwazi
nameSuffix: -elwazi
resources:
  - ../../base
labels:
  - pairs:
      app: data-catalogue-elwazi
    includeSelectors: true
configMapGenerator:
  - name: app-config
    files:
      - config.js
    options:
      disableNameSuffixHash: true
  - name: nginx-config
    files:
      - nginx.conf
    options:
      disableNameSuffixHash: true

secretGenerator:
  - name: docker-registry-secret
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=.dockerconfig.json
    options:
      disableNameSuffixHash: true

# a patch to make sure the service account
# and docker repo secret do not get renamed
patchesJson6902:
  - target:
      version: v1
      kind: ServiceAccount
      name: default
    patch: |-
      - op: replace
        path: /metadata/name
        value: default
  - target:
      version: v1
      kind: Secret
      name: docker-registry-secret
    patch: |-
      - op: replace
        path: /metadata/name
        value: docker-registry-secret
