apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dc-elwazi
nameSuffix: -elwazi
resources:
  - https://github.com/ebi-ait/data-catalogue-frontend/k8s/base?ref=feature/dc-11-deploy-on-demo-env
labels:
  - includeSelectors: true
    pairs:
      app: data-catalogue-elwazi

configMapGenerator:
  - files:
      - config.js
    name: app-config
    options:
      disableNameSuffixHash: true
  - files:
      - nginx.conf
    name: nginx-config
    options:
      disableNameSuffixHash: true
secretGenerator:
  - name: docker-registry-secret
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=.dockerconfig.json
    options:
      disableNameSuffixHash: true

# a patch to make sure the service account
# and docker repo secret do not get renamed
patchesJson6902:
- patch: |-
    - op: replace
      path: /metadata/name
      value: default
  target:
      kind: ServiceAccount
      name: default
      version: v1
- patch: |-
      - op: replace
        path: /metadata/name
        value: docker-registry-secret
  target:
      kind: Secret
      name: docker-registry-secret
      version: v1
- patch: |-
    - op: replace
      path: /metadata/name
      value: ingress
    - op: replace
      path: /spec/rules/0/http/paths/0/path
      value: /catalogue/demo(/|$)(.*)
  target:
    kind: Ingress
    name: ingress
    version: v1
images:
- name: data-catalogue-demo
  newName: dockerhub.ebi.ac.uk/fairification/data-catalogue-demo
  newTag: 20240328-1219
